# Generated by Django 4.1.7 on 2023-03-25 17:16

from django.db import migrations
import owner_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': owner_admin.models.Offers},
        ),
    ]
