# Generated by Django 4.1.7 on 2023-03-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'Offers'},
        ),
    ]
