# Generated by Django 4.1.7 on 2023-03-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
