# Generated by Django 4.1.7 on 2023-03-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
