# Generated by Django 4.1.7 on 2023-03-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_admin', '0003_alter_offers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Offers'},
        ),
    ]
