# Generated by Django 4.1.7 on 2023-03-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_admin', '0005_offers_spots_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='to_date',
        ),
    ]
