# Generated by Django 4.1.7 on 2023-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_admin', '0006_offers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
