# Generated by Django 4.1.7 on 2023-03-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_admin', '0006_rename_from_date_offers_date_remove_offers_to_date'),
        ('owner_admin', '0007_alter_offers_location'),
    ]

    operations = [
    ]
